language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - node
  - "lts/*"
  - "8.9.0"
  - "8.16.0"
  - "9.11.2"
  - "10.16.0"

before_script:
  - greenkeeper-lockfile-update

after_script: greenkeeper-lockfile-upload

branches:
  except:
    - /^v\d+\.\d+\.\d+$/

stages:
  - lint
  - test
  - release

jobs:
  include:
    - stage: lint
      script: npm run lint
    - stage: test
      script: npm test
    - stage: release
      node_js: node
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release

install: npm install
